from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from mk8d import db
from mk8d.models import Cup, Track, CupTrack


engine = create_engine("sqlite:///site.db")
Session = sessionmaker(bind=engine)
session = Session()

data = [
#     # Original cups
#     Cup(name="Mushroom", description=""),
#     Cup(name="Flower", description=""),
#     Cup(name="Star", description=""),
#     Cup(name="Special", description=""),
#     Cup(name="Shell", description=""),
#     Cup(name="Banana", description=""),
#     Cup(name="Leaf", description=""),
#     Cup(name="Lightning", description=""),
#     Cup(name="Egg", description=""),
#     Cup(name="Crossing", description=""),
#     Cup(name="Triforce", description=""),
#     Cup(name="Bell", description=""),
#     Cup(name="Golden Dash", description=""),
#     Cup(name="Lucky Cat", description=""),
#     Cup(name="Turnip", description=""),
#     Cup(name="Propeller", description=""),
#
#     # New themed cups
#     Cup(name="Town", description=""),
#     Cup(name="Building", description=""),
#     Cup(name="Topographic", description=""),
#     Cup(name="Sky", description=""),
#     Cup(name="City", description=""),
#     Cup(name="Castle", description=""),
#     Cup(name="Snow", description=""),
#     Cup(name="Desert", description=""),
#     Cup(name="Underwater", description=""),
#     Cup(name="Sci-Fi", description=""),
#     Cup(name="Mario", description=""),
#
#
#     # Tracks
#     Track(name="Mario Kart Stadium", original_cup=1),
#     Track(name="Water Park", original_cup=1),
#     Track(name="Sweet Sweet Canyon", original_cup=1),
#     Track(name="Thwomp Ruins", original_cup=1),
#     Track(name="Mario Circuit", original_cup=2),
#     Track(name="Toad Harbor", original_cup=2),
#     Track(name="Twisted Mansion", original_cup=2),
#     Track(name="Shy Guy Falls", original_cup=2),
#     Track(name="Sunshine Airport", original_cup=3),
#     Track(name="Dolphin Shoals", original_cup=3),
#     Track(name="Electrodrome", original_cup=3),
#     Track(name="Mount Wario", original_cup=3),
#     Track(name="Cloudtop Cruise", original_cup=4),
#     Track(name="Bone-Dry Dunes", original_cup=4),
#     Track(name="Bowser's Castle", original_cup=4),
#     Track(name="Rainbow Road", original_cup=4),
#     Track(name="Moo Moo Meadows", original_cup=5),
#     Track(name="Mario Circuit", original_cup=5),
#     Track(name="Cheep Cheep Beach", original_cup=5),
#     Track(name="Toad's Turnpike", original_cup=5),
#     Track(name="Dry Dry Desert", original_cup=6),
#     Track(name="Donut Plains 3", original_cup=6),
#     Track(name="Royal Raceway", original_cup=6),
#     Track(name="DK Jungle", original_cup=6),
#     Track(name="Wario Stadium", original_cup=7),
#     Track(name="Sherbet Land", original_cup=7),
#     Track(name="Music Park", original_cup=7),
#     Track(name="Yoshi Valley", original_cup=7),
#     Track(name="Tick-Tock Clock", original_cup=8),
#     Track(name="Piranha Plant Slide", original_cup=8),
#     Track(name="Grumble Volcano", original_cup=8),
#     Track(name="Rainbow Road", original_cup=8),
#     Track(name="Yoshi Circuit", original_cup=9),
#     Track(name="Excitebike Arena", original_cup=9),
#     Track(name="Dragon Driftway", original_cup=9),
#     Track(name="Mute City", original_cup=9),
#     Track(name="Baby Park", original_cup=10),
#     Track(name="Cheese Land", original_cup=10),
#     Track(name="Wild Woods", original_cup=10),
#     Track(name="Animal Crossing", original_cup=10),
#     Track(name="Wario's Gold Mine", original_cup=11),
#     Track(name="Rainbow Road", original_cup=11),
#     Track(name="Ice Ice Outpost", original_cup=11),
#     Track(name="Hyrule Circuit", original_cup=11),
#     Track(name="Neo Bowser City", original_cup=12),
#     Track(name="Ribbon Road", original_cup=12),
#     Track(name="Super Bell Subway", original_cup=12),
#     Track(name="Big Blue", original_cup=12),
#     Track(name="Paris Promenade", original_cup=13),
#     Track(name="Toad Circuit", original_cup=13),
#     Track(name="Choco Mountain", original_cup=13),
#     Track(name="Coconut Mall", original_cup=13),
#     Track(name="Tokyo Blur", original_cup=14),
#     Track(name="Shroom Ridge", original_cup=14),
#     Track(name="Sky Garden", original_cup=14),
#     Track(name="Ninja Hideaway", original_cup=14),
#     Track(name="New York Minute", original_cup=15),
#     Track(name="Mario Circuit 3", original_cup=15),
#     Track(name="Kalimari Desert", original_cup=15),
#     Track(name="Waluigi Pinball", original_cup=15),
#     Track(name="Sydney Sprint", original_cup=16),
#     Track(name="Snow Land", original_cup=16),
#     Track(name="Mushroom Gorge", original_cup=16),
#     Track(name="Sky-High Sundae", original_cup=16),
#
#
#     # Original cups and tracks
#     CupTrack(cup_id=1, track_id=1, track_order=1),
#     CupTrack(cup_id=1, track_id=2, track_order=2),
#     CupTrack(cup_id=1, track_id=3, track_order=3),
#     CupTrack(cup_id=1, track_id=4, track_order=4),
#     CupTrack(cup_id=2, track_id=5, track_order=1),
#     CupTrack(cup_id=2, track_id=6, track_order=2),
#     CupTrack(cup_id=2, track_id=7, track_order=3),
#     CupTrack(cup_id=2, track_id=8, track_order=4),
#     CupTrack(cup_id=3, track_id=9, track_order=1),
#     CupTrack(cup_id=3, track_id=10, track_order=2),
#     CupTrack(cup_id=3, track_id=11, track_order=3),
#     CupTrack(cup_id=3, track_id=12, track_order=4),
#     CupTrack(cup_id=4, track_id=13, track_order=1),
#     CupTrack(cup_id=4, track_id=14, track_order=2),
#     CupTrack(cup_id=4, track_id=15, track_order=3),
#     CupTrack(cup_id=4, track_id=16, track_order=4),
#     CupTrack(cup_id=5, track_id=17, track_order=1),
#     CupTrack(cup_id=5, track_id=18, track_order=2),
#     CupTrack(cup_id=5, track_id=19, track_order=3),
#     CupTrack(cup_id=5, track_id=20, track_order=4),
#     CupTrack(cup_id=6, track_id=21, track_order=1),
#     CupTrack(cup_id=6, track_id=22, track_order=2),
#     CupTrack(cup_id=6, track_id=23, track_order=3),
#     CupTrack(cup_id=6, track_id=24, track_order=4),
#     CupTrack(cup_id=7, track_id=25, track_order=1),
#     CupTrack(cup_id=7, track_id=26, track_order=2),
#     CupTrack(cup_id=7, track_id=27, track_order=3),
#     CupTrack(cup_id=7, track_id=28, track_order=4),
#     CupTrack(cup_id=8, track_id=29, track_order=1),
#     CupTrack(cup_id=8, track_id=30, track_order=2),
#     CupTrack(cup_id=8, track_id=31, track_order=3),
#     CupTrack(cup_id=8, track_id=32, track_order=4),
#     CupTrack(cup_id=9, track_id=33, track_order=1),
#     CupTrack(cup_id=9, track_id=34, track_order=2),
#     CupTrack(cup_id=9, track_id=35, track_order=3),
#     CupTrack(cup_id=9, track_id=36, track_order=4),
#     CupTrack(cup_id=10, track_id=37, track_order=1),
#     CupTrack(cup_id=10, track_id=38, track_order=2),
#     CupTrack(cup_id=10, track_id=39, track_order=3),
#     CupTrack(cup_id=10, track_id=40, track_order=4),
#     CupTrack(cup_id=11, track_id=41, track_order=1),
#     CupTrack(cup_id=11, track_id=42, track_order=2),
#     CupTrack(cup_id=11, track_id=43, track_order=3),
#     CupTrack(cup_id=11, track_id=44, track_order=4),
#     CupTrack(cup_id=12, track_id=45, track_order=1),
#     CupTrack(cup_id=12, track_id=46, track_order=2),
#     CupTrack(cup_id=12, track_id=47, track_order=3),
#     CupTrack(cup_id=12, track_id=48, track_order=4),
#     CupTrack(cup_id=13, track_id=49, track_order=1),
#     CupTrack(cup_id=13, track_id=50, track_order=2),
#     CupTrack(cup_id=13, track_id=51, track_order=3),
#     CupTrack(cup_id=13, track_id=52, track_order=4),
#     CupTrack(cup_id=14, track_id=53, track_order=1),
#     CupTrack(cup_id=14, track_id=54, track_order=2),
#     CupTrack(cup_id=14, track_id=55, track_order=3),
#     CupTrack(cup_id=14, track_id=56, track_order=4),
#     CupTrack(cup_id=15, track_id=57, track_order=1),
#     CupTrack(cup_id=15, track_id=58, track_order=2),
#     CupTrack(cup_id=15, track_id=59, track_order=3),
#     CupTrack(cup_id=15, track_id=60, track_order=4),
#     CupTrack(cup_id=16, track_id=61, track_order=1),
#     CupTrack(cup_id=16, track_id=62, track_order=2),
#     CupTrack(cup_id=16, track_id=63, track_order=3),
#     CupTrack(cup_id=16, track_id=64, track_order=4),
#
#     # New themed cups and tracks
#     CupTrack(cup_id=17, track_id=33, track_order=1),
#     CupTrack(cup_id=17, track_id=40, track_order=2),
#     CupTrack(cup_id=17, track_id=39, track_order=3),
#     CupTrack(cup_id=17, track_id=6, track_order=4),
#     CupTrack(cup_id=18, track_id=56, track_order=1),
#     CupTrack(cup_id=18, track_id=7, track_order=2),
#     CupTrack(cup_id=18, track_id=52, track_order=3),
#     CupTrack(cup_id=18, track_id=15, track_order=4),
#     CupTrack(cup_id=19, track_id=28, track_order=1),
#     CupTrack(cup_id=19, track_id=63, track_order=2),
#     CupTrack(cup_id=19, track_id=51, track_order=3),
#     CupTrack(cup_id=19, track_id=54, track_order=4),
#     CupTrack(cup_id=20, track_id=55, track_order=1),
#     CupTrack(cup_id=20, track_id=64, track_order=2),
#     CupTrack(cup_id=20, track_id=32, track_order=3),
#     CupTrack(cup_id=20, track_id=13, track_order=4),
#     CupTrack(cup_id=20, track_id=42, track_order=5),
#     CupTrack(cup_id=21, track_id=53, track_order=1),
#     CupTrack(cup_id=21, track_id=61, track_order=2),
#     CupTrack(cup_id=21, track_id=45, track_order=3),
#     CupTrack(cup_id=21, track_id=20, track_order=4),
#     CupTrack(cup_id=21, track_id=49, track_order=5),
#     CupTrack(cup_id=21, track_id=57, track_order=6),
#     CupTrack(cup_id=21, track_id=36, track_order=7),
#     CupTrack(cup_id=22, track_id=5, track_order=1),
#     CupTrack(cup_id=22, track_id=44, track_order=2),
#     CupTrack(cup_id=22, track_id=15, track_order=3),
#     CupTrack(cup_id=22, track_id=37, track_order=4),
#     CupTrack(cup_id=22, track_id=23, track_order=5),
#     CupTrack(cup_id=23, track_id=62, track_order=1),
#     CupTrack(cup_id=23, track_id=43, track_order=2),
#     CupTrack(cup_id=23, track_id=26, track_order=3),
#     CupTrack(cup_id=23, track_id=12, track_order=4),
#     CupTrack(cup_id=24, track_id=21, track_order=1),
#     CupTrack(cup_id=24, track_id=14, track_order=2),
#     CupTrack(cup_id=24, track_id=38, track_order=3),
#     CupTrack(cup_id=24, track_id=59, track_order=4),
#     CupTrack(cup_id=25, track_id=2, track_order=1),
#     CupTrack(cup_id=25, track_id=7, track_order=2),
#     CupTrack(cup_id=25, track_id=25, track_order=3),
#     CupTrack(cup_id=25, track_id=3, track_order=4),
#     CupTrack(cup_id=25, track_id=10, track_order=5),
#     CupTrack(cup_id=26, track_id=36, track_order=1),
#     CupTrack(cup_id=26, track_id=16, track_order=2),
#     CupTrack(cup_id=26, track_id=45, track_order=3),
#     CupTrack(cup_id=26, track_id=48, track_order=4),
#     CupTrack(cup_id=27, track_id=58, track_order=1),
#     CupTrack(cup_id=27, track_id=18, track_order=2),
#     CupTrack(cup_id=27, track_id=5, track_order=3),
    CupTrack(cup_id=27, track_id=1, track_order=4)
]

session.add_all(data)
session.commit()
session.close()
engine.dispose()
